### ISSUE TITLE
Links on README.md are missing

### ISSUE THREAD

**Issue by bobdemp** [Sliicy/8x8x8-LED#6]
Hi

I am looking to try you modified firmware as I think it is what I need.  The links don't work?

https://github.com/Sliicy/ledcube8x8x8/blob/master/firmware/v2-sdcc-icubesmart/firmware.ihx

Can you fix them?

Thanks

**Comment by Sliicy** [comment]
Hi @bobdemp, thank you for pointing this out. I went ahead and corrected all the links in my latest commit, and that firmware can be found under the Firmware/Monochrome/[8x8x8 Monochrome Cube Firmware.ihx](https://github.com/Sliicy/8x8x8-LED/blob/master/Firmware/Monochrome/8x8x8%20Monochrome%20Cube%20Firmware.ihx). It was renamed for clarity (since firmware.ihx is too broad). Keep in mind that this specific file is for monochromatic (single color) cubes only.
